OSSAdmiral/Recruit

- app/Http/Kernel.php
- app/Models/User.php
- composer.json
- composer.lock
- config/app.php
- config/permission.php
- database/migrations/2023_07_21_020941_create_permission_tables.php
- database/seeders/DatabaseSeeder.php
- database/seeders/RoleSeeder.php
- database/seeders/UserSeeder.php
- routes/web.php
The following files that has been added are:
**DatabaseSeeder.php** (database/seeders/DatabaseSeeder.php)
**UserSeeder.php** (database/seeders/UserSeeder.php)
In the UserSeeder I added a script to create a user with random details. And UserSeeder is being called in DatabaseSeeder.
> Created a Seeder File and name it as UserSeeder

- .github/dependabot.yml
- .github/workflows/auto-assign.yml
- .github/workflows/dependabot-auto-merge.yml
- .github/workflows/update-changelog.yml
- CHANGELOG.md
> added Github workflow :zap:

- README.md
- composer.lock
> Updated README.md

- routes/api.php
remove sanctum middleware :hammer:
> remove sanctum middleware :hammer:

- app/Filament/Resources/DepartmentsResource.php
- app/Filament/Resources/DepartmentsResource/Pages/CreateDepartments.php
- app/Filament/Resources/DepartmentsResource/Pages/EditDepartments.php
- app/Filament/Resources/DepartmentsResource/Pages/ListDepartments.php
- app/Filament/Resources/DepartmentsResource/Pages/ViewDepartments.php
- app/Filament/Resources/JobOpeningsResource.php
- app/Http/Controllers/departmentsController.php
- app/Models/Departments.php
- app/Models/JobOpenings.php
- composer.json
- composer.lock
- database/factories/departmentsFactory.php
- database/migrations/2023_08_07_115631_create_job_openings_table.php
- database/migrations/2023_08_10_122745_create_departments_table.php
> WIP :hammer:

- app/Filament/Resources/CandidatesProfileResource.php
- app/Filament/Resources/CandidatesProfileResource/Pages/CreateCandidatesProfile.php
- app/Filament/Resources/CandidatesProfileResource/Pages/EditCandidatesProfile.php
- app/Filament/Resources/CandidatesProfileResource/Pages/ListCandidatesProfiles.php
- app/Filament/Resources/CandidatesProfileResource/Pages/ViewCandidatesProfile.php
- app/Http/Controllers/CandidatesController.php
- app/Models/Candidates.php
- database/migrations/2023_08_10_135333_create_candidates_table.php
> Candidates Module

- app/Providers/Filament/AdminPanelProvider.php
- routes/web.php
change the route to default by removing other index route
> chore(Change route to default)

- .github/workflows/fix-php-code-style-issues.yml
- .github/workflows/run-tests.yml
- composer.json
- composer.lock
- tests/Feature/ExampleTest.php
- tests/Pest.php
added GitHub action for test and fix code style :shirt: :zap:
> added GitHub action for test and fix code style :shirt: :zap:

- .github/workflows/run-tests.yml
- composer.json
- composer.lock
- database/seeders/RoleSeeder.php
- tests/Feature/LoginPageTest.php
_Please provide description of the PR_
- 🎫 Related Issue #42 
- 🔐 Closes #42 
> 42 testcase login page

- .github/workflows/run-tests.yml
- app/Filament/Enums/JobCandidateStatus.php
- app/Filament/Resources/JobCandidatesResource.php
- app/Filament/Resources/JobCandidatesResource/Pages/CreateJobCandidates.php
- app/Filament/Resources/JobCandidatesResource/Pages/EditJobCandidates.php
- app/Filament/Resources/JobCandidatesResource/Pages/ListJobCandidates.php
- app/Filament/Resources/JobCandidatesResource/Pages/ViewJobCandidates.php
- app/Http/Controllers/JobCandidatesController.php
- app/Models/JobCandidates.php
- database/factories/JobCandidatesFactory.php
- database/migrations/2023_08_13_124543_create_job_candidates_table.php
:sparkles: Added module for Job Candidates
> 23 job candidates module

- app/Filament/Enums/AttachmentCategory.php
- app/Filament/Resources/CandidatesProfileResource.php
- app/Filament/Resources/CandidatesProfileResource/RelationManagers/AttachmentsRelationManager.php
- app/Filament/Resources/DepartmentsResource.php
- app/Filament/Resources/DepartmentsResource/RelationManagers/AttachmentsRelationManager.php
- app/Filament/Resources/JobCandidatesResource.php
- app/Filament/Resources/JobCandidatesResource/Pages/EditJobCandidates.php
- app/Filament/Resources/JobCandidatesResource/RelationManagers/AttachmentsRelationManager.php
- app/Filament/Resources/JobOpeningsResource.php
- app/Filament/Resources/JobOpeningsResource/Pages/EditJobOpenings.php
- app/Filament/Resources/JobOpeningsResource/RelationManagers/AttachmentsRelationManager.php
- app/Models/Attachments.php
- app/Models/Candidates.php
- app/Models/Departments.php
- app/Models/JobCandidates.php
- app/Models/JobOpenings.php
- database/migrations/2023_08_16_170431_create_attachments_table.php
Added new feature `Attachments` as related list for all the module.
- 🎫 Related Issue #47 
- 🔐 Closes #47 
> Attachment Related list

- app/Filament/Resources/CandidatesProfileResource/RelationManagers/AttachmentsRelationManager.php
- app/Filament/Resources/DepartmentsResource/RelationManagers/AttachmentsRelationManager.php
- app/Filament/Resources/JobCandidatesResource/RelationManagers/AttachmentsRelationManager.php
- app/Filament/Resources/JobOpeningsResource/RelationManagers/AttachmentsRelationManager.php
Enhanced the attachment related list and be able to have preview as an options, added image MIME Type for image
- 🎫 Related Issue #
- 🔐 Closes #
> Attachment Related list Enhancement

- app/Filament/Resources/ReferralsResource.php
- app/Filament/Resources/ReferralsResource/Pages/CreateReferrals.php
- app/Filament/Resources/ReferralsResource/Pages/EditReferrals.php
- app/Filament/Resources/ReferralsResource/Pages/ListReferrals.php
- app/Filament/Resources/ReferralsResource/Pages/ViewReferrals.php
- app/Http/Controllers/ReferralsController.php
- app/Models/Referrals.php
- database/migrations/2023_08_17_111204_create_referrals_table.php
Added new modules
- 🎫 Related Issue #19 
- 🔐 Closes #19 
> 19 referrals module

- app/Filament/Enums/AttachmentCategory.php
- app/Filament/Resources/JobCandidatesResource.php
- app/Models/Departments.php
- app/Models/JobCandidates.php
- app/Models/JobOpenings.php
- app/Models/User.php
change to recordOwner for the relation name as it take confusion on the model
Closes #57
_Please provide description of the PR_
- 🎫 Related Issue #57
- 🔐 Closes #57 
> fix(Model Relation):

- database/migrations/2023_08_07_115631_create_job_openings_table.php
Added new column for publish to career site
- 🎫 Related Issue #
- 🔐 Closes #
> added new column published to career site

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
[Describe in plain language what changes/additional you made and why.]
[Closes #IssueNumber]  
[Attach screenshots or images here to visually show the changes, if relevant.]
[Share any additional information or thoughts here.]
> Revert "Delete .github/ISSUE_TEMPLATE directory"

- app/Models/Candidates.php
- database/factories/CandidatesFactory.php
added candidate auto number and factory
[Closes #56 ]
> added candidate auto number and factory

- app/Filament/Resources/JobCandidatesResource.php
- app/Filament/Resources/UserResource.php
- app/Filament/Resources/UserResource/Pages/CreateUser.php
- app/Filament/Resources/UserResource/Pages/EditUser.php
- app/Filament/Resources/UserResource/Pages/ListUsers.php
- app/Filament/Resources/UserResource/Pages/ViewUser.php
- app/Models/User.php
- app/Providers/Filament/AdminPanelProvider.php
- composer.json
- composer.lock
- config/authentication-log.php
- config/filament-authentication-log.php
- database/migrations/2014_10_12_000000_create_users_table.php
- database/migrations/2023_09_21_034627_create_authentication_log_table.php
- lang/vendor/filament-authentication-log/en/filament-authentication-log.php
> User resource

- README.md
- app/Filament/Resources/UserResource.php
- app/Models/User.php
- app/Policies/AttachmentsPolicy.php
- app/Policies/CandidatesPolicy.php
- app/Policies/DepartmentsPolicy.php
- app/Policies/JobCandidatesPolicy.php
- app/Policies/JobOpeningsPolicy.php
- app/Policies/ReferralsPolicy.php
- app/Policies/UserPolicy.php
- app/Providers/AuthServiceProvider.php
- app/Providers/Filament/AdminPanelProvider.php
- composer.json
- composer.lock
- config/filament-spatie-roles-permissions.php
- database/seeders/DatabaseSeeder.php
> Roles and Permissions

- app/Providers/Filament/AdminPanelProvider.php
- resources/views/filament/pages/auth/login.blade.php
added render hook to add the candidate login route in the login page
> added render hook to add the candidate login route in the login page

- app/Filament/Candidate/Pages/MyResumeProfile.php
- app/Filament/Candidate/Resources/AppliedJobListResource.php
- app/Filament/Candidate/Resources/AppliedJobListResource/Pages/ListAppliedJobLists.php
- app/Filament/Candidate/Resources/JobOpeningsResource.php
- app/Filament/Candidate/Resources/SavedJobResource.php
- app/Filament/Enums/AttachmentCategory.php
- app/Filament/Enums/JobCandidateStatus.php
- app/Filament/Enums/JobOpeningStatus.php
- app/Traits/EnumToArray.php
This module will show all the job that the candidate applied with the current status of their applications for the job.
None
> Added applied job module

- app/Filament/Resources/UserResource.php
- app/Filament/Resources/UserResource/Pages/CreateUser.php
- app/Filament/Resources/UserResource/Pages/ListUsers.php
- app/Livewire/Portal/Invitation/CreateCandidateUser.php
- app/Livewire/User/Invitation/CreateSystemUserForm.php
- app/Models/User.php
- app/Notifications/User/InviteNewSystemUserNotification.php
- app/Notifications/User/WelcomeSystemUserNotification.php
- database/migrations/2023_11_04_223939_add_joined_and_sent_column_at_users.php
- database/migrations/2023_11_04_234719_add_invitation_uuid_at_users.php
- resources/views/livewire/user/invitation/create-system-user.blade.php
- routes/web.php
Added a invitation user only feature
[Closes #98 ]  
[Attach screenshots or images here to visually show the changes, if relevant.]
[Share any additional information or thoughts here.]
> Feature add system user via invitation only

- app/Filament/Resources/JobOpeningsResource.php
- app/Models/JobOpenings.php
- database/migrations/2024_05_06_042913_add_additional_note_to_table_job_openings.php
Add notes to the job opening
[Closes #124 ]
> 124 add notes text fields in job application

- app/Providers/Filament/AdminPanelProvider.php
- app/Providers/Filament/CandidatePanelProvider.php
Add single page application `spa` feature to panels, that enhance performance when navigation between panels pages
- [ x] I have read and followed the project's contribution guidelines.
- [ x] My code follows the project's style and conventions.
- [x ] I've tested my changes to make sure they work.
- [ x] I've added or updated any necessary documentation.
- [ x] I've checked for and resolved any merge conflicts.
> feat: add `spa` feature to filement panel
